import { RealEstate, Luxury, NFTAsset } from '../store/gameStore';

export const INITIAL_REAL_ESTATE: RealEstate[] = [
  {
    "id": "house_econom_barbican_estate_uk",
    "name": "Barbican Estate",
    "location": "UK",
    "cost": 75000,
    "rent": 45,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 37500,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Barbican Estate — UK.jpg"
  },
  {
    "id": "house_econom_dubai_simple_apartment",
    "name": "Dubai Simple Apartment",
    "location": "Dubai, UAE",
    "cost": 114286,
    "rent": 69,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 57143,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Dubai Simple Apartment.jpg"
  },
  {
    "id": "house_econom_london_basic_flat",
    "name": "London Basic Flat",
    "location": "London, UK",
    "cost": 153571,
    "rent": 92,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 76786,
    "class": "economy",
    "imageUrl": "EconomClassHouse/London Basic Flat.jpg"
  },
  {
    "id": "house_econom_paris_habitat_france",
    "name": "Paris Habitat",
    "location": "France",
    "cost": 192857,
    "rent": 116,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 96429,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Paris Habitat — France.jpg"
  },
  {
    "id": "house_econom_seoul_mini_residence",
    "name": "Seoul Mini Residence",
    "location": "Seoul, South Korea",
    "cost": 232143,
    "rent": 139,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 116072,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Seoul Mini Residence.jpg"
  },
  {
    "id": "house_econom_stuyvesant_town_new_york_usa",
    "name": "Stuyvesant Town",
    "location": "New York, USA",
    "cost": 271429,
    "rent": 163,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 135715,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Stuyvesant Town — New York, USA.webp"
  },
  {
    "id": "house_econom_stuyvesant_town_usa",
    "name": "Stuyvesant Town",
    "location": "USA",
    "cost": 310714,
    "rent": 186,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 155357,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Stuyvesant Town — USA.jpg"
  },
  {
    "id": "house_econom_tokyo_residence_japan",
    "name": "Tokyo Residence",
    "location": "Japan",
    "cost": 350000,
    "rent": 210,
    "count": 0,
    "icon": "home",
    "upgradeLevel": 1,
    "upgradeCost": 175000,
    "class": "economy",
    "imageUrl": "EconomClassHouse/Tokyo Residence — Japan.jpg"
  },
  {
    "id": "house_luxe_alpine_luxury_chalet",
    "name": "Alpine Luxury Chalet",
    "location": "Alps, Switzerland",
    "cost": 19000000,
    "rent": 13300,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 11400000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Alpine Luxury Chalet.jpg"
  },
  {
    "id": "house_luxe_antilia_mumbai_india",
    "name": "Antilia, Mumbai, India",
    "location": "India",
    "cost": 1400000000,
    "rent": 980000,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 840000000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Antilia, Mumbai, India.jpg"
  },
  {
    "id": "house_luxe_beverly_hills_mansion",
    "name": "Beverly Hills Mansion",
    "location": "Beverly Hills, USA",
    "cost": 29000000,
    "rent": 20300,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 17400000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Beverly Hills Mansion.jpg"
  },
  {
    "id": "house_luxe_dubai_royal_villa",
    "name": "Dubai Royal Villa",
    "location": "Dubai, UAE",
    "cost": 8500000,
    "rent": 5950,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 5100000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Dubai Royal Villa.jpg"
  },
  {
    "id": "house_luxe_dubai_villa",
    "name": "Dubai Villa",
    "location": "Dubai, UAE",
    "cost": 4500000,
    "rent": 3150,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 2700000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Dubai Villa.jpg"
  },
  {
    "id": "house_luxe_french_riviera_palace",
    "name": "French Riviera Palace",
    "location": "French Riviera, France",
    "cost": 165000000,
    "rent": 115500,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 99000000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/French Riviera Palace.jpg"
  },
  {
    "id": "house_luxe_lake_como_grand_villa",
    "name": "Lake Como Grand Villa",
    "location": "Lake Como, Italy",
    "cost": 48000000,
    "rent": 33600,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 28800000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Lake Como Grand Villa.jpg"
  },
  {
    "id": "house_luxe_london_royal_mansion",
    "name": "London Royal Mansion",
    "location": "London, UK",
    "cost": 98000000,
    "rent": 68600,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 58800000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/London Royal Mansion.jpg"
  },
  {
    "id": "house_luxe_marbella_golden_villa",
    "name": "Marbella Golden Villa",
    "location": "Marbella, Spain",
    "cost": 13500000,
    "rent": 9450,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 8100000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Marbella Golden Villa.jpg"
  },
  {
    "id": "house_luxe_villa_leopolda_france",
    "name": "Villa Leopolda, France",
    "location": "France",
    "cost": 650000000,
    "rent": 455000,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 390000000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Villa Leopolda, France.jpg"
  },
  {
    "id": "house_luxe_villa_les_cedres_french_riviera_france",
    "name": "Villa Les Cedres, French Riviera, France",
    "location": "France",
    "cost": 350000000,
    "rent": 245000,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 210000000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Villa Les Cedres, French Riviera, France.jpg"
  },
  {
    "id": "house_luxe_villa_monaco",
    "name": "Villa Monaco",
    "location": "Monaco",
    "cost": 68000000,
    "rent": 47600,
    "count": 0,
    "icon": "building",
    "upgradeLevel": 1,
    "upgradeCost": 40800000,
    "class": "luxury",
    "imageUrl": "LuxeClassHouse/Villa Monaco.jpg"
  }
];

export const INITIAL_LUXURY: Luxury[] = [
  {
    "id": "car_econom_belgee_x50",
    "name": "Belgee X50",
    "cost": 6500,
    "prestige": 43,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Belgee X50.jpg"
  },
  {
    "id": "car_econom_changan_alsvin",
    "name": "Changan Alsvin",
    "cost": 7222,
    "prestige": 48,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Changan Alsvin.jpg"
  },
  {
    "id": "car_econom_chery_tiggo_4_pro",
    "name": "Chery Tiggo 4 Pro",
    "cost": 7944,
    "prestige": 53,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Chery Tiggo 4 Pro.jpg"
  },
  {
    "id": "car_econom_chery_tiggo_4",
    "name": "Chery Tiggo 4",
    "cost": 8667,
    "prestige": 58,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Chery Tiggo 4.jpg"
  },
  {
    "id": "car_econom_chevrolet_aveo",
    "name": "Chevrolet Aveo",
    "cost": 9389,
    "prestige": 63,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Chevrolet Aveo.jpg"
  },
  {
    "id": "car_econom_datsun_mi_do",
    "name": "Datsun mi-DO",
    "cost": 10111,
    "prestige": 67,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Datsun mi-DO.jpg"
  },
  {
    "id": "car_econom_datsun_on_do",
    "name": "Datsun on-DO",
    "cost": 10833,
    "prestige": 72,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Datsun on-DO.jpg"
  },
  {
    "id": "car_econom_geely_emgrand",
    "name": "Geely Emgrand",
    "cost": 11556,
    "prestige": 77,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Geely Emgrand.jpg"
  },
  {
    "id": "car_econom_haval_m6",
    "name": "Haval M6",
    "cost": 12278,
    "prestige": 82,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Haval M6.jpg"
  },
  {
    "id": "car_econom_hyundai_solaris",
    "name": "Hyundai Solaris",
    "cost": 13000,
    "prestige": 87,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Hyundai Solaris.jpg"
  },
  {
    "id": "car_econom_kia_rio",
    "name": "Kia Rio",
    "cost": 13722,
    "prestige": 91,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Kia Rio.jpg"
  },
  {
    "id": "car_econom_lada_granta",
    "name": "Lada Granta",
    "cost": 14444,
    "prestige": 96,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Lada Granta.jpg"
  },
  {
    "id": "car_econom_lada_vesta",
    "name": "Lada Vesta",
    "cost": 15167,
    "prestige": 101,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Lada Vesta.jpg"
  },
  {
    "id": "car_econom_nissan_almera",
    "name": "Nissan Almera",
    "cost": 15889,
    "prestige": 106,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Nissan Almera.jpg"
  },
  {
    "id": "car_econom_renault_logan",
    "name": "Renault Logan",
    "cost": 16611,
    "prestige": 111,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Renault Logan.jpg"
  },
  {
    "id": "car_econom_renault_sandero",
    "name": "Renault Sandero",
    "cost": 17333,
    "prestige": 116,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Renault Sandero.jpg"
  },
  {
    "id": "car_econom_skoda_rapid",
    "name": "Skoda Rapid",
    "cost": 18056,
    "prestige": 120,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Skoda Rapid.JPG"
  },
  {
    "id": "car_econom_volkswagen_polo",
    "name": "Volkswagen Polo",
    "cost": 18778,
    "prestige": 125,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/Volkswagen Polo.jpg"
  },
  {
    "id": "car_econom_e8004ab28600f062cd704c31e8837ebd",
    "name": "e8004ab28600f062cd704c31e8837ebd",
    "cost": 19500,
    "prestige": 130,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "economy",
    "imageUrl": "EconomClassAuto/e8004ab28600f062cd704c31e8837ebd.png"
  },
  {
    "id": "car_comfort_citro_n_c4",
    "name": "Citroën C4",
    "cost": 22000,
    "prestige": 220,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Citroën C4.jpg"
  },
  {
    "id": "car_comfort_honda_civic",
    "name": "Honda Civic",
    "cost": 25286,
    "prestige": 253,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Honda Civic.jpg"
  },
  {
    "id": "car_comfort_hyundai_elantra",
    "name": "Hyundai Elantra",
    "cost": 28571,
    "prestige": 286,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Hyundai Elantra.jpg"
  },
  {
    "id": "car_comfort_hyundai_tucson",
    "name": "Hyundai Tucson",
    "cost": 31857,
    "prestige": 319,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Hyundai Tucson.jpg"
  },
  {
    "id": "car_comfort_kia_cerato_forte",
    "name": "Kia Cerato (Forte)",
    "cost": 35143,
    "prestige": 351,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Kia Cerato (Forte).jpg"
  },
  {
    "id": "car_comfort_lada_largus",
    "name": "Lada Largus",
    "cost": 38429,
    "prestige": 384,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Lada Largus.jpg"
  },
  {
    "id": "car_comfort_mazda_3",
    "name": "Mazda 3",
    "cost": 41714,
    "prestige": 417,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Mazda 3.jpg"
  },
  {
    "id": "car_comfort_nissan_sentra",
    "name": "Nissan Sentra",
    "cost": 45000,
    "prestige": 450,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Nissan Sentra.jpg"
  },
  {
    "id": "car_comfort_nissan_sylphy",
    "name": "Nissan Sylphy",
    "cost": 48286,
    "prestige": 483,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Nissan Sylphy.jpg"
  },
  {
    "id": "car_comfort_peugeot_308",
    "name": "Peugeot 308",
    "cost": 51571,
    "prestige": 516,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Peugeot 308.jpg"
  },
  {
    "id": "car_comfort_renault_megane",
    "name": "Renault Megane",
    "cost": 54857,
    "prestige": 549,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Renault Megane.jpg"
  },
  {
    "id": "car_comfort_skoda_octavia",
    "name": "Skoda Octavia",
    "cost": 58143,
    "prestige": 581,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Skoda Octavia.jpg"
  },
  {
    "id": "car_comfort_subaru_impreza",
    "name": "Subaru Impreza",
    "cost": 61429,
    "prestige": 614,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Subaru Impreza.jpg"
  },
  {
    "id": "car_comfort_toyota_prius",
    "name": "Toyota Prius",
    "cost": 64714,
    "prestige": 647,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Toyota Prius.jpg"
  },
  {
    "id": "car_comfort_volkswagen_jetta",
    "name": "Volkswagen Jetta",
    "cost": 68000,
    "prestige": 680,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "medium",
    "imageUrl": "ComfortClassAuto/Volkswagen Jetta.jpg"
  },
  {
    "id": "car_luxe_aston_martin_db12",
    "name": "Aston Martin DB12",
    "cost": 90000,
    "prestige": 1500,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Aston Martin DB12.jpg"
  },
  {
    "id": "car_luxe_audi_a8",
    "name": "Audi A8",
    "cost": 107368,
    "prestige": 1789,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Audi A8.jpg"
  },
  {
    "id": "car_luxe_bmw_7_series",
    "name": "BMW 7 Series",
    "cost": 124737,
    "prestige": 2079,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/BMW 7 Series.jpg"
  },
  {
    "id": "car_luxe_bmw_xm",
    "name": "BMW XM",
    "cost": 142105,
    "prestige": 2368,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/BMW XM.jpg"
  },
  {
    "id": "car_luxe_bentley_flying_spur",
    "name": "Bentley Flying Spur",
    "cost": 159474,
    "prestige": 2658,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Bentley Flying Spur.jpg"
  },
  {
    "id": "car_luxe_bentley_mulsanne",
    "name": "Bentley Mulsanne",
    "cost": 176842,
    "prestige": 2947,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Bentley Mulsanne.jpg"
  },
  {
    "id": "car_luxe_cadillac_escalade_2026",
    "name": "Cadillac Escalade 2026",
    "cost": 194211,
    "prestige": 3237,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Cadillac Escalade 2026.jpg"
  },
  {
    "id": "car_luxe_ferrari_roma",
    "name": "Ferrari Roma",
    "cost": 211579,
    "prestige": 3526,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Ferrari Roma.jpg"
  },
  {
    "id": "car_luxe_genesis_g90",
    "name": "Genesis G90",
    "cost": 228947,
    "prestige": 3816,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Genesis G90.jpg"
  },
  {
    "id": "car_luxe_lamborghini_urus",
    "name": "Lamborghini Urus",
    "cost": 246316,
    "prestige": 4105,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Lamborghini Urus.jpg"
  },
  {
    "id": "car_luxe_lexus_ls",
    "name": "Lexus LS",
    "cost": 263684,
    "prestige": 4395,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Lexus LS.jpg"
  },
  {
    "id": "car_luxe_lexus_lx",
    "name": "Lexus LX",
    "cost": 281053,
    "prestige": 4684,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Lexus LX.jpg"
  },
  {
    "id": "car_luxe_maserati_quattroporte",
    "name": "Maserati Quattroporte",
    "cost": 298421,
    "prestige": 4974,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Maserati Quattroporte.jpg"
  },
  {
    "id": "car_luxe_mercedes_benz_s_class",
    "name": "Mercedes-Benz S-Class",
    "cost": 315789,
    "prestige": 5263,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Mercedes-Benz S-Class.jpg"
  },
  {
    "id": "car_luxe_mercedes_maybach_s_class",
    "name": "Mercedes-Maybach S-Class",
    "cost": 333158,
    "prestige": 5553,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Mercedes-Maybach S-Class.jpg"
  },
  {
    "id": "car_luxe_porsche_cayenne_turbo_gt",
    "name": "Porsche Cayenne Turbo GT",
    "cost": 350526,
    "prestige": 5842,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Porsche Cayenne Turbo GT.jpg"
  },
  {
    "id": "car_luxe_porsche_panamera",
    "name": "Porsche Panamera",
    "cost": 367895,
    "prestige": 6132,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Porsche Panamera.jpg"
  },
  {
    "id": "car_luxe_range_rover_sv",
    "name": "Range Rover SV",
    "cost": 385263,
    "prestige": 6421,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Range Rover SV.jpg"
  },
  {
    "id": "car_luxe_rolls_royce_ghost",
    "name": "Rolls-Royce Ghost",
    "cost": 402632,
    "prestige": 6711,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Rolls-Royce Ghost.jpg"
  },
  {
    "id": "car_luxe_rolls_royce_phantom",
    "name": "Rolls-Royce Phantom",
    "cost": 420000,
    "prestige": 7000,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "LuxeClassAuto/Rolls-Royce Phantom"
  },
  {
    "id": "car_ultraluxury_aston_martin_valkyrie",
    "name": "Aston Martin Valkyrie",
    "cost": 1200000,
    "prestige": 30000,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Aston Martin Valkyrie.jpg"
  },
  {
    "id": "car_ultraluxury_bugatti_bolide",
    "name": "Bugatti Bolide",
    "cost": 1435714,
    "prestige": 35893,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Bugatti Bolide.jpg"
  },
  {
    "id": "car_ultraluxury_bugatti_chiron_super_sport",
    "name": "Bugatti Chiron Super Sport",
    "cost": 1671429,
    "prestige": 41786,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Bugatti Chiron Super Sport.jpg"
  },
  {
    "id": "car_ultraluxury_bugatti_tourbillon",
    "name": "Bugatti Tourbillon",
    "cost": 1907143,
    "prestige": 47679,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Bugatti Tourbillon.jpg"
  },
  {
    "id": "car_ultraluxury_ferrari_f80",
    "name": "Ferrari F80",
    "cost": 2142857,
    "prestige": 53571,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Ferrari F80.jpg"
  },
  {
    "id": "car_ultraluxury_ferrari_laferrari",
    "name": "Ferrari LaFerrari",
    "cost": 2378571,
    "prestige": 59464,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Ferrari LaFerrari.jpg"
  },
  {
    "id": "car_ultraluxury_koenigsegg_gemera",
    "name": "Koenigsegg Gemera",
    "cost": 2614286,
    "prestige": 65357,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Koenigsegg Gemera.jpg"
  },
  {
    "id": "car_ultraluxury_koenigsegg_jesko_absolut",
    "name": "Koenigsegg Jesko Absolut",
    "cost": 2850000,
    "prestige": 71250,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Koenigsegg Jesko Absolut.jpg"
  },
  {
    "id": "car_ultraluxury_lamborghini_revuelto",
    "name": "Lamborghini Revuelto",
    "cost": 3085714,
    "prestige": 77143,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Lamborghini Revuelto.jpg"
  },
  {
    "id": "car_ultraluxury_mclaren_speedtail",
    "name": "McLaren Speedtail",
    "cost": 3321429,
    "prestige": 83036,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/McLaren Speedtail.jpg"
  },
  {
    "id": "car_ultraluxury_mclaren_w1",
    "name": "McLaren W1",
    "cost": 3557143,
    "prestige": 88929,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/McLaren W1.jpg"
  },
  {
    "id": "car_ultraluxury_mercedes_amg_one",
    "name": "Mercedes-AMG ONE",
    "cost": 3792857,
    "prestige": 94821,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Mercedes-AMG ONE.jpg"
  },
  {
    "id": "car_ultraluxury_pagani_huayra_r",
    "name": "Pagani Huayra R",
    "cost": 4028571,
    "prestige": 100714,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Pagani Huayra R.jpg"
  },
  {
    "id": "car_ultraluxury_pagani_utopia",
    "name": "Pagani Utopia",
    "cost": 4264286,
    "prestige": 106607,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Pagani Utopia.jpg"
  },
  {
    "id": "car_ultraluxury_rimac_nevera",
    "name": "Rimac Nevera",
    "cost": 4500000,
    "prestige": 112500,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "luxury",
    "imageUrl": "UltraLuxuryClassAuto/Rimac Nevera.jpg"
  },
  {
    "id": "car_3ultraexpensivelegendaryrare_bugatti_type_57_sc_atlantic",
    "name": "Bugatti Type 57 SC Atlantic",
    "cost": 45000000,
    "prestige": 1800000,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "collectible",
    "imageUrl": "3UltraExpensiveLegendaryRareClassAuto/Bugatti Type 57 SC Atlantic.jpg"
  },
  {
    "id": "car_3ultraexpensivelegendaryrare_ferrari_250_gto",
    "name": "Ferrari 250 GTO",
    "cost": 85000000,
    "prestige": 3400000,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "collectible",
    "imageUrl": "3UltraExpensiveLegendaryRareClassAuto/Ferrari 250 GTO.jpg"
  },
  {
    "id": "car_3ultraexpensivelegendaryrare_mercedes_benz_300_slr_uhlenhaut_coup",
    "name": "Mercedes-Benz 300 SLR Uhlenhaut Coupé",
    "cost": 142000000,
    "prestige": 5680000,
    "count": 0,
    "icon": "car",
    "category": "car",
    "class": "collectible",
    "imageUrl": "3UltraExpensiveLegendaryRareClassAuto/Mercedes-Benz 300 SLR Uhlenhaut Coupé.jpg"
  },
  {
    "id": "yacht_yakthstandart_aegean_sea_yacht",
    "name": "Aegean Sea Yacht",
    "cost": 380000,
    "prestige": 7600,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/Aegean Sea Yacht.jpg"
  },
  {
    "id": "yacht_yakthstandart_bosphorus_luxury_boat",
    "name": "Bosphorus Luxury Boat",
    "cost": 794000,
    "prestige": 15880,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/Bosphorus Luxury Boat.jpg"
  },
  {
    "id": "yacht_yakthstandart_french_coast_yacht",
    "name": "French Coast Yacht",
    "cost": 1208000,
    "prestige": 24160,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/French Coast Yacht.jpg"
  },
  {
    "id": "yacht_yakthstandart_miami_cruiser_yacht",
    "name": "Miami Cruiser Yacht",
    "cost": 1622000,
    "prestige": 32440,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/Miami Cruiser Yacht.jpg"
  },
  {
    "id": "yacht_yakthstandart_sydney_ocean_yacht",
    "name": "Sydney Ocean Yacht",
    "cost": 2036000,
    "prestige": 40720,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/Sydney Ocean Yacht.jpg"
  },
  {
    "id": "yacht_yakthstandart_venice_sport_yacht",
    "name": "Venice Sport Yacht",
    "cost": 2450000,
    "prestige": 49000,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "medium",
    "imageUrl": "YakthClassStandart/Venice Sport Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_beverly_ocean_yacht",
    "name": "Beverly Ocean Yacht",
    "cost": 12000000,
    "prestige": 400000,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Beverly Ocean Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_cannes_elite_yacht",
    "name": "Cannes Elite Yacht",
    "cost": 77600000,
    "prestige": 2586667,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Cannes Elite Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_dubai_diamond_yacht",
    "name": "Dubai Diamond Yacht",
    "cost": 143200000,
    "prestige": 4773333,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Dubai Diamond Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_italian_majesty_yacht",
    "name": "Italian Majesty Yacht",
    "cost": 208800000,
    "prestige": 6960000,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Italian Majesty Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_monaco_royal_yacht",
    "name": "Monaco Royal Yacht",
    "cost": 274400000,
    "prestige": 9146667,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Monaco Royal Yacht.jpg"
  },
  {
    "id": "yacht_luxuryyakthts_singapore_grand_yacht",
    "name": "Singapore Grand Yacht",
    "cost": 340000000,
    "prestige": 11333333,
    "count": 0,
    "icon": "ship",
    "category": "yacht",
    "class": "luxury",
    "imageUrl": "LuxuryYakthts/Singapore Grand Yacht.jpg"
  },
  {
    "id": "plane_eco_1",
    "name": "Single-Engine Propeller",
    "cost": 120000,
    "prestige": 120,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1527706363292-7bfcfd0d124c?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_eco_2",
    "name": "Ultralight Recreational Flyer",
    "cost": 180000,
    "prestige": 200,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1498084393753-b411b2d26b34?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_eco_3",
    "name": "Utility Turboprop",
    "cost": 320000,
    "prestige": 380,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_eco_4",
    "name": "Amphibious Seaplane",
    "cost": 450000,
    "prestige": 550,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_eco_5",
    "name": "Vintage Biplane Scout",
    "cost": 600000,
    "prestige": 800,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1527706363292-7bfcfd0d124c?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_med_1",
    "name": "Twin-Engine Light Jet",
    "cost": 1500000,
    "prestige": 2200,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_med_2",
    "name": "Executive Turboprop Commuter",
    "cost": 2800000,
    "prestige": 4200,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_med_3",
    "name": "Private Helicopter Bell T1",
    "cost": 4500000,
    "prestige": 7500,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_med_4",
    "name": "Regional Charter Jet",
    "cost": 7800000,
    "prestige": 14000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_med_5",
    "name": "Light Cargo Transporter",
    "cost": 11000000,
    "prestige": 22000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1498084393753-b411b2d26b34?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_lux_1",
    "name": "Heavy Long-Range Gulf-Jet",
    "cost": 25000000,
    "prestige": 55000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_lux_2",
    "name": "Supersonic Business Cruiser",
    "cost": 60000000,
    "prestige": 150000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_lux_3",
    "name": "Stealth Personal Jet",
    "cost": 110000000,
    "prestige": 320000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_lux_4",
    "name": "VIP Double-Deck Jumbo Jet",
    "cost": 240000000,
    "prestige": 800000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "plane_lux_5",
    "name": "Solid Gold Intercontinental Airliner",
    "cost": 550000000,
    "prestige": 2000000,
    "count": 0,
    "icon": "plane",
    "category": "plane",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_gold_bar",
    "name": "Gold Bullion Bar (1kg)",
    "cost": 65000,
    "prestige": 80,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1610375228911-c4ab02318010?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_platinum_ingot",
    "name": "Platinum Ingot",
    "cost": 95000,
    "prestige": 130,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_emerald_ring",
    "name": "Imperial Emerald Ring",
    "cost": 140000,
    "prestige": 220,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "economy",
    "imageUrl": "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_sapphire_tiara",
    "name": "Royal Sapphire Tiara",
    "cost": 280000,
    "prestige": 500,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_diamond_necklace",
    "name": "Premium Diamond Cascade",
    "cost": 450000,
    "prestige": 900,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_faberge_egg",
    "name": "Imperial Faberge Egg",
    "cost": 850000,
    "prestige": 1800,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "medium",
    "imageUrl": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "art_renaissance",
    "name": "Classic Renaissance Oil Painting",
    "cost": 1800000,
    "prestige": 4000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "art_sculpture",
    "name": "Ancient Marble Statue",
    "cost": 3200000,
    "prestige": 7500,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "art_impressionist",
    "name": "French Impressionist Masterpiece",
    "cost": 6500000,
    "prestige": 16000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "jew_crown_jewels",
    "name": "Historic Monarch Crown",
    "cost": 15000000,
    "prestige": 45000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "art_picasso",
    "name": "Surrealist Masterpiece Painting",
    "cost": 45000000,
    "prestige": 150000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "art_mona_lisa",
    "name": "The Louvre Original Masterpiece",
    "cost": 120000000,
    "prestige": 500000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "relic_excalibur",
    "name": "Ancient Excalibur Sword",
    "cost": 250000000,
    "prestige": 1200000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "relic_ark",
    "name": "Covenant Gilded Relic",
    "cost": 600000000,
    "prestige": 3500000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1610375228911-c4ab02318010?w=500&auto=format&fit=crop&q=60"
  },
  {
    "id": "relic_grail",
    "name": "Holy Platinum Chalice",
    "cost": 1500000000,
    "prestige": 10000000,
    "count": 0,
    "icon": "gem",
    "category": "jewelry",
    "class": "luxury",
    "imageUrl": "https://images.unsplash.com/photo-1610375228911-c4ab02318010?w=500&auto=format&fit=crop&q=60"
  }
];

export const INITIAL_NFTS: NFTAsset[] = [
  {
    "id": "bored_ape",
    "name": "Bored Ape Clone #4920",
    "costETH": 15,
    "prestige": 1200,
    "count": 0,
    "icon": "smile",
    "color": "#F7931A"
  },
  {
    "id": "cryptopunk",
    "name": "Punk Pixel Clone #883",
    "costETH": 65,
    "prestige": 6000,
    "count": 0,
    "icon": "smile",
    "color": "#627EEA"
  },
  {
    "id": "gold_yacht_nft",
    "name": "Golden Yacht NFT Collectible",
    "costETH": 280,
    "prestige": 29000,
    "count": 0,
    "icon": "ship",
    "color": "#F3BA2F"
  },
  {
    "id": "space_shuttle_nft",
    "name": "Pixel Shuttle Space NFT",
    "costETH": 950,
    "prestige": 110000,
    "count": 0,
    "icon": "rocket",
    "color": "#9945FF"
  }
];
