// Auto-generated local image registry
export const LOCAL_IMAGES: Record<string, any> = {
  "3UltraExpensiveLegendaryRareClassAuto/Bugatti Type 57 SC Atlantic.jpg": require("../images/3UltraExpensiveLegendaryRareClassAuto/Bugatti Type 57 SC Atlantic.jpg"),
  "3UltraExpensiveLegendaryRareClassAuto/Ferrari 250 GTO.jpg": require("../images/3UltraExpensiveLegendaryRareClassAuto/Ferrari 250 GTO.jpg"),
  "3UltraExpensiveLegendaryRareClassAuto/Mercedes-Benz 300 SLR Uhlenhaut Coupé.jpg": require("../images/3UltraExpensiveLegendaryRareClassAuto/Mercedes-Benz 300 SLR Uhlenhaut Coupé.jpg"),
  "ComfortClassAuto/Citroën C4.jpg": require("../images/ComfortClassAuto/Citroën C4.jpg"),
  "ComfortClassAuto/Honda Civic.jpg": require("../images/ComfortClassAuto/Honda Civic.jpg"),
  "ComfortClassAuto/Hyundai Elantra.jpg": require("../images/ComfortClassAuto/Hyundai Elantra.jpg"),
  "ComfortClassAuto/Hyundai Tucson.jpg": require("../images/ComfortClassAuto/Hyundai Tucson.jpg"),
  "ComfortClassAuto/Kia Cerato (Forte).jpg": require("../images/ComfortClassAuto/Kia Cerato (Forte).jpg"),
  "ComfortClassAuto/Lada Largus.jpg": require("../images/ComfortClassAuto/Lada Largus.jpg"),
  "ComfortClassAuto/Mazda 3.jpg": require("../images/ComfortClassAuto/Mazda 3.jpg"),
  "ComfortClassAuto/Nissan Sentra.jpg": require("../images/ComfortClassAuto/Nissan Sentra.jpg"),
  "ComfortClassAuto/Nissan Sylphy.jpg": require("../images/ComfortClassAuto/Nissan Sylphy.jpg"),
  "ComfortClassAuto/Peugeot 308.jpg": require("../images/ComfortClassAuto/Peugeot 308.jpg"),
  "ComfortClassAuto/Renault Megane.jpg": require("../images/ComfortClassAuto/Renault Megane.jpg"),
  "ComfortClassAuto/Skoda Octavia.jpg": require("../images/ComfortClassAuto/Skoda Octavia.jpg"),
  "ComfortClassAuto/Subaru Impreza.jpg": require("../images/ComfortClassAuto/Subaru Impreza.jpg"),
  "ComfortClassAuto/Toyota Prius.jpg": require("../images/ComfortClassAuto/Toyota Prius.jpg"),
  "ComfortClassAuto/Volkswagen Jetta.jpg": require("../images/ComfortClassAuto/Volkswagen Jetta.jpg"),
  "EconomClassAuto/Belgee X50.jpg": require("../images/EconomClassAuto/Belgee X50.jpg"),
  "EconomClassAuto/Changan Alsvin.jpg": require("../images/EconomClassAuto/Changan Alsvin.jpg"),
  "EconomClassAuto/Chery Tiggo 4 Pro.jpg": require("../images/EconomClassAuto/Chery Tiggo 4 Pro.jpg"),
  "EconomClassAuto/Chery Tiggo 4.jpg": require("../images/EconomClassAuto/Chery Tiggo 4.jpg"),
  "EconomClassAuto/Chevrolet Aveo.jpg": require("../images/EconomClassAuto/Chevrolet Aveo.jpg"),
  "EconomClassAuto/Datsun mi-DO.jpg": require("../images/EconomClassAuto/Datsun mi-DO.jpg"),
  "EconomClassAuto/Datsun on-DO.jpg": require("../images/EconomClassAuto/Datsun on-DO.jpg"),
  "EconomClassAuto/e8004ab28600f062cd704c31e8837ebd.png": require("../images/EconomClassAuto/e8004ab28600f062cd704c31e8837ebd.png"),
  "EconomClassAuto/Geely Emgrand.jpg": require("../images/EconomClassAuto/Geely Emgrand.jpg"),
  "EconomClassAuto/Haval M6.jpg": require("../images/EconomClassAuto/Haval M6.jpg"),
  "EconomClassAuto/Hyundai Solaris.jpg": require("../images/EconomClassAuto/Hyundai Solaris.jpg"),
  "EconomClassAuto/Kia Rio.jpg": require("../images/EconomClassAuto/Kia Rio.jpg"),
  "EconomClassAuto/Lada Granta.jpg": require("../images/EconomClassAuto/Lada Granta.jpg"),
  "EconomClassAuto/Lada Vesta.jpg": require("../images/EconomClassAuto/Lada Vesta.jpg"),
  "EconomClassAuto/Nissan Almera.jpg": require("../images/EconomClassAuto/Nissan Almera.jpg"),
  "EconomClassAuto/Renault Logan.jpg": require("../images/EconomClassAuto/Renault Logan.jpg"),
  "EconomClassAuto/Renault Sandero.jpg": require("../images/EconomClassAuto/Renault Sandero.jpg"),
  "EconomClassAuto/Skoda Rapid.jpg": require("../images/EconomClassAuto/Skoda Rapid.jpg"),
  "EconomClassAuto/Volkswagen Polo.jpg": require("../images/EconomClassAuto/Volkswagen Polo.jpg"),
  "EconomClassHouse/Barbican Estate — UK.jpg": require("../images/EconomClassHouse/Barbican Estate — UK.jpg"),
  "EconomClassHouse/Dubai Simple Apartment.jpg": require("../images/EconomClassHouse/Dubai Simple Apartment.jpg"),
  "EconomClassHouse/London Basic Flat.jpg": require("../images/EconomClassHouse/London Basic Flat.jpg"),
  "EconomClassHouse/Paris Habitat — France.jpg": require("../images/EconomClassHouse/Paris Habitat — France.jpg"),
  "EconomClassHouse/Seoul Mini Residence.jpg": require("../images/EconomClassHouse/Seoul Mini Residence.jpg"),
  "EconomClassHouse/Stuyvesant Town — New York, USA.webp": require("../images/EconomClassHouse/Stuyvesant Town — New York, USA.webp"),
  "EconomClassHouse/Stuyvesant Town — USA.jpg": require("../images/EconomClassHouse/Stuyvesant Town — USA.jpg"),
  "EconomClassHouse/Tokyo Residence — Japan.jpg": require("../images/EconomClassHouse/Tokyo Residence — Japan.jpg"),
  "LuxeClassAuto/Aston Martin DB12.jpg": require("../images/LuxeClassAuto/Aston Martin DB12.jpg"),
  "LuxeClassAuto/Audi A8.jpg": require("../images/LuxeClassAuto/Audi A8.jpg"),
  "LuxeClassAuto/Bentley Flying Spur.jpg": require("../images/LuxeClassAuto/Bentley Flying Spur.jpg"),
  "LuxeClassAuto/Bentley Mulsanne.jpg": require("../images/LuxeClassAuto/Bentley Mulsanne.jpg"),
  "LuxeClassAuto/BMW 7 Series.jpg": require("../images/LuxeClassAuto/BMW 7 Series.jpg"),
  "LuxeClassAuto/BMW XM.jpg": require("../images/LuxeClassAuto/BMW XM.jpg"),
  "LuxeClassAuto/Cadillac Escalade 2026.jpg": require("../images/LuxeClassAuto/Cadillac Escalade 2026.jpg"),
  "LuxeClassAuto/Ferrari Roma.jpg": require("../images/LuxeClassAuto/Ferrari Roma.jpg"),
  "LuxeClassAuto/Genesis G90.jpg": require("../images/LuxeClassAuto/Genesis G90.jpg"),
  "LuxeClassAuto/Lamborghini Urus.jpg": require("../images/LuxeClassAuto/Lamborghini Urus.jpg"),
  "LuxeClassAuto/Lexus LS.jpg": require("../images/LuxeClassAuto/Lexus LS.jpg"),
  "LuxeClassAuto/Lexus LX.jpg": require("../images/LuxeClassAuto/Lexus LX.jpg"),
  "LuxeClassAuto/Maserati Quattroporte.jpg": require("../images/LuxeClassAuto/Maserati Quattroporte.jpg"),
  "LuxeClassAuto/Mercedes-Benz S-Class.jpg": require("../images/LuxeClassAuto/Mercedes-Benz S-Class.jpg"),
  "LuxeClassAuto/Mercedes-Maybach S-Class.jpg": require("../images/LuxeClassAuto/Mercedes-Maybach S-Class.jpg"),
  "LuxeClassAuto/Porsche Cayenne Turbo GT.jpg": require("../images/LuxeClassAuto/Porsche Cayenne Turbo GT.jpg"),
  "LuxeClassAuto/Porsche Panamera.jpg": require("../images/LuxeClassAuto/Porsche Panamera.jpg"),
  "LuxeClassAuto/Range Rover SV.jpg": require("../images/LuxeClassAuto/Range Rover SV.jpg"),
  "LuxeClassAuto/Rolls-Royce Ghost.jpg": require("../images/LuxeClassAuto/Rolls-Royce Ghost.jpg"),
  "LuxeClassAuto/Rolls-Royce Phantom.jpg": require("../images/LuxeClassAuto/Rolls-Royce Phantom.jpg"),
  "LuxeClassHouse/Alpine Luxury Chalet.jpg": require("../images/LuxeClassHouse/Alpine Luxury Chalet.jpg"),
  "LuxeClassHouse/Antilia, Mumbai, India.jpg": require("../images/LuxeClassHouse/Antilia, Mumbai, India.jpg"),
  "LuxeClassHouse/Beverly Hills Mansion.jpg": require("../images/LuxeClassHouse/Beverly Hills Mansion.jpg"),
  "LuxeClassHouse/Dubai Royal Villa.jpg": require("../images/LuxeClassHouse/Dubai Royal Villa.jpg"),
  "LuxeClassHouse/Dubai Villa.jpg": require("../images/LuxeClassHouse/Dubai Villa.jpg"),
  "LuxeClassHouse/French Riviera Palace.jpg": require("../images/LuxeClassHouse/French Riviera Palace.jpg"),
  "LuxeClassHouse/Lake Como Grand Villa.jpg": require("../images/LuxeClassHouse/Lake Como Grand Villa.jpg"),
  "LuxeClassHouse/London Royal Mansion.jpg": require("../images/LuxeClassHouse/London Royal Mansion.jpg"),
  "LuxeClassHouse/Marbella Golden Villa.jpg": require("../images/LuxeClassHouse/Marbella Golden Villa.jpg"),
  "LuxeClassHouse/Villa Leopolda, France.jpg": require("../images/LuxeClassHouse/Villa Leopolda, France.jpg"),
  "LuxeClassHouse/Villa Les Cedres, French Riviera, France.jpg": require("../images/LuxeClassHouse/Villa Les Cedres, French Riviera, France.jpg"),
  "LuxeClassHouse/Villa Monaco.jpg": require("../images/LuxeClassHouse/Villa Monaco.jpg"),
  "LuxuryYakthts/Beverly Ocean Yacht.jpg": require("../images/LuxuryYakthts/Beverly Ocean Yacht.jpg"),
  "LuxuryYakthts/Cannes Elite Yacht.jpg": require("../images/LuxuryYakthts/Cannes Elite Yacht.jpg"),
  "LuxuryYakthts/Dubai Diamond Yacht.jpg": require("../images/LuxuryYakthts/Dubai Diamond Yacht.jpg"),
  "LuxuryYakthts/Italian Majesty Yacht.jpg": require("../images/LuxuryYakthts/Italian Majesty Yacht.jpg"),
  "LuxuryYakthts/Monaco Royal Yacht.jpg": require("../images/LuxuryYakthts/Monaco Royal Yacht.jpg"),
  "LuxuryYakthts/Singapore Grand Yacht.jpg": require("../images/LuxuryYakthts/Singapore Grand Yacht.jpg"),
  "UltraLuxuryClassAuto/Aston Martin Valkyrie.jpg": require("../images/UltraLuxuryClassAuto/Aston Martin Valkyrie.jpg"),
  "UltraLuxuryClassAuto/Bugatti Bolide.jpg": require("../images/UltraLuxuryClassAuto/Bugatti Bolide.jpg"),
  "UltraLuxuryClassAuto/Bugatti Chiron Super Sport.jpg": require("../images/UltraLuxuryClassAuto/Bugatti Chiron Super Sport.jpg"),
  "UltraLuxuryClassAuto/Bugatti Tourbillon.jpg": require("../images/UltraLuxuryClassAuto/Bugatti Tourbillon.jpg"),
  "UltraLuxuryClassAuto/Ferrari F80.jpg": require("../images/UltraLuxuryClassAuto/Ferrari F80.jpg"),
  "UltraLuxuryClassAuto/Ferrari LaFerrari.jpg": require("../images/UltraLuxuryClassAuto/Ferrari LaFerrari.jpg"),
  "UltraLuxuryClassAuto/Koenigsegg Gemera.jpg": require("../images/UltraLuxuryClassAuto/Koenigsegg Gemera.jpg"),
  "UltraLuxuryClassAuto/Koenigsegg Jesko Absolut.jpg": require("../images/UltraLuxuryClassAuto/Koenigsegg Jesko Absolut.jpg"),
  "UltraLuxuryClassAuto/Lamborghini Revuelto.jpg": require("../images/UltraLuxuryClassAuto/Lamborghini Revuelto.jpg"),
  "UltraLuxuryClassAuto/McLaren Speedtail.jpg": require("../images/UltraLuxuryClassAuto/McLaren Speedtail.jpg"),
  "UltraLuxuryClassAuto/McLaren W1.jpg": require("../images/UltraLuxuryClassAuto/McLaren W1.jpg"),
  "UltraLuxuryClassAuto/Mercedes-AMG ONE.jpg": require("../images/UltraLuxuryClassAuto/Mercedes-AMG ONE.jpg"),
  "UltraLuxuryClassAuto/Pagani Huayra R.jpg": require("../images/UltraLuxuryClassAuto/Pagani Huayra R.jpg"),
  "UltraLuxuryClassAuto/Pagani Utopia.jpg": require("../images/UltraLuxuryClassAuto/Pagani Utopia.jpg"),
  "UltraLuxuryClassAuto/Rimac Nevera.jpg": require("../images/UltraLuxuryClassAuto/Rimac Nevera.jpg"),
  "YakthClassStandart/Aegean Sea Yacht.jpg": require("../images/YakthClassStandart/Aegean Sea Yacht.jpg"),
  "YakthClassStandart/Bosphorus Luxury Boat.jpg": require("../images/YakthClassStandart/Bosphorus Luxury Boat.jpg"),
  "YakthClassStandart/French Coast Yacht.jpg": require("../images/YakthClassStandart/French Coast Yacht.jpg"),
  "YakthClassStandart/Miami Cruiser Yacht.jpg": require("../images/YakthClassStandart/Miami Cruiser Yacht.jpg"),
  "YakthClassStandart/Sydney Ocean Yacht.jpg": require("../images/YakthClassStandart/Sydney Ocean Yacht.jpg"),
  "YakthClassStandart/Venice Sport Yacht.jpg": require("../images/YakthClassStandart/Venice Sport Yacht.jpg"),
};